# Project Title: Alternative Credit Scoring System
## Subtitle: A Predictive Model for Household Loan Default Risk using the 2021 FinAccess Survey
**Author:** PAUL – Level 300 Applied Math & CS, Kenyatta University

---

### 1. Project Overview
This project develops a **practitioner-level credit scoring engine** designed to assess the creditworthiness of Kenyan individuals. By leveraging the **2021 FinAccess Household Survey**, the model moves beyond traditional collateral-based lending to explore **alternative data**—including mobile money usage (M-Shwari, Fuliza), psychographic financial behavior, and household economic resilience.

### 2. The Problem Statement
Despite high mobile money penetration in Kenya, a significant portion of the population remains **"thin-file"** (lacking a traditional credit history). For institutions like Safaricom or Tier 1 Banks, the challenge is to accurately predict the probability of default ($PD$) using survey-based behavioral proxies. Inaccurate scoring leads to high **Non-Performing Loans (NPLs)** or financial exclusion for deserving borrowers.

### 3. Objectives
* **Target Definition:** Quantify "Financial Distress" using markers like late repayments, asset liquidation, and meal-skipping due to debt.
* **Feature Engineering:** Extract high-signal predictors from mobile banking frequency, informal (*Chama*) involvement, and demographic stability.
* **Modeling:** Train a binary classification model to differentiate between "Low Risk" and "High Risk" individuals.
* **Deployment Readiness:** Evaluate the model using banking metrics: ROC-AUC, Gini Coefficient, and Precision-Recall curves.

### 4. Data Source
The dataset is the **2021 FinAccess Household Survey (Weighted)**, a national representative survey of 22,000+ households conducted by the **Kenya National Bureau of Statistics (KNBS)** and the **Central Bank of Kenya (CBK)**.

##  PHASE 1:DATA CLEANING

## 1. Data loading

In [1]:
# importing the libraries
import pandas as pd
import pyreadstat

In [2]:
# we load the data and the metadata
df,meta =pyreadstat.read_sav('C:/Users/Win/Alternative credit scoring/Data/Updated Anonymized Weighted FinAccess 2021.sav')

In [3]:
#lets preview or dataset
df.head()

,County,ClusterNo,HHNo,interview__key,interview__id,A9,A9i,A10i,A14v,A14vi,...,excl_mob_bank_acc2,excl_fuliza,excl_bank_mobile_users2,comb_mob_bank_acc,uninsured_NHIF,Saving_groups,A1,has_tele,gave_tele,hasagr
0,26.0,10226038.0,1048.0,10-67-89-46,0003fc74b3fe418ea041bd6a9e7ff387,1.0,1.0,2.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,1.0,TRANS NZOIA,1.0,1.0,1.0
1,40.0,10240034.0,1080.0,39-64-68-81,0004890b17744272baf0a0c7b4c20771,1.0,1.0,2.0,4.0,2.0,...,0.0,0.0,4.0,0.0,0.0,1.0,BUSIA,1.0,1.0,0.0
2,16.0,10216062.0,1013.0,92-34-74-01,00052153fe8c4abaa189caadcb87b2b4,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,4.0,0.0,0.0,1.0,MACHAKOS,0.0,0.0,1.0
3,42.0,10242078.0,1026.0,08-14-22-63,000d1f8747194b6a84862830dc5fe7ca,1.0,1.0,1.0,5.0,4.0,...,0.0,0.0,4.0,0.0,1.0,0.0,KISUMU,1.0,1.0,0.0
4,21.0,10221166.0,1096.0,03-40-25-90,0010697b1e454d1cb38c60acacc249dd,2.0,1.0,1.0,2.0,1.0,...,0.0,0.0,4.0,1.0,1.0,1.0,MURANG'A,1.0,1.0,0.0

In [4]:
#lets see the shape of our dataset
print(f" The dataset has: (rows , columns) {df.shape}")

 The dataset has: (rows , columns) (22024, 2353)

In [5]:
#lets get a simple summary of our dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22024 entries, 0 to 22023
Columns: 2353 entries, County to hasagr
dtypes: float64(2190), object(163)
memory usage: 395.4+ MB

In [6]:
#lets check for duplicates
df.duplicated().sum()

np.int64(0)

In [7]:
df.isnull().sum()

County            0
ClusterNo         0
HHNo              0
interview__key    0
interview__id     0
                 ..
Saving_groups     0
A1                0
has_tele          0
gave_tele         0
hasagr            0
Length: 2353, dtype: int64

## 2. Target Variable Engineering

In [8]:
# we now search the metadata for risk indicators,bu searching for keywords in the column labels
keywords=['loan','default','late','miss','repay','refuse','borrow']
#k means key:column name in our dataset
#v means value:label or description of the column
risk_related={k:v for k,v in meta.column_names_to_labels.items()
              if any (word in v.lower()for word in keywords)}
#we display our findings
for col,label in risk_related.items():
    print(f"{col}:{label}|")

B1B4:B1B4. Loan Security|
B1C3:B1C3. Frequency miss an important family event|
B1EF99:B1EF99. Refused to Answer(DO NOT READ OUT)|
B3D__99:B3D__99  Refused to Answer (DO NOT READ OUT)|
C1_2:C1-2. Savings through mobile banking (e.g. Mshwari , KCB MPesa, MCoop cash, Eazzy Loan, Timiza, HF Whizz)?|
C1_10:C1_10. Registered on Mobile bank (e.g. Mshwari , KCB MPesa, MCoop cash, Eazzy Loan, Timiza, HF Whizz)|
C1_11:C1_11. Personal loan/business loan from a bank|
C1_12:C1_12. Loan from mobile banking (e.g. Mshwari , KCB MPesa, MCoop cash, Eazzy Loan, Timiza, HF Whizz, Stawi loan, M-fanisi)|
C1_13:C1_13. Loan from mobile money provider (e.g Fuliza loan)|
C1_14:C1_14. Loan at a Sacco / Savings and Credit Cooperative organisation|
C1_15:C1_15. Loan from a microfinance institution|
C1_16:C1_16. Loan from Shylocks / Loan Sharks / Money Lenders / Money Merchants that are not from your phone (e.g. Platinum, Ngao, etc.)|
C1_17:C1_17. Loan from a group/chama|
C1_18:C1_18. Loan from a government institution for education, agriculture or devt|
C1_19:C1_19. Loan from an employer|
C1_20:C1-20. Loan from family/friend/neighbour|
C1_21:C1-21. Cash loan from shopkeeper|
C1_23:C1-23 Digital loans that you get through the phone that you download through apps (e.g. Branch, Tala, Utunzi, Haraka loans, etc.)|
C1_24:C1-24 Loan / credits from buyer of your harvest / supplier of agricultural inputs (e.g. coffee, tea, sugarcane, tobacco, vegetables)|
C1_26:C1-26. Loan from Insurance|
C1_27:C1-27. Loan to buy / build a house (mortgage), or to buy land from a bank / building society or Sacco/Insurance/Government|
C2_12:C2_12. Loan from mobile banking|
C2_13:C2_13. Mobile money loans (e.g Fuliza). Did you use this in the last 12 months?|
D1i__11:D1i__11  They refused to pay my pension|
D1i__99:D1i__99  Refused to Answer (DO NOT READ OUT)|
D1B__12:D1B__12  They refused to pay my insurance claim|
D1B__99:D1B__99  Refused to Answer (DO NOT READ OUT)|
D1C__12:D1C__12  They refused to pay my insurance claim|
D1C__99:D1C__99  Refused to Answer (DO NOT READ OUT)|
D3__99:D3__99  Refused to Answer (DO NOT READ OUT)|
D5__6:D5__6  Compulsory for this policy provider (loan,mortgage,fire,life)|
D5__99:D5__99  Refused to Answer(DO NOT READ OUT)|
E1:E1. Whether Tried and Failed to Take a Loan|
E2__4:E2__4  Mobile banking (e.g. Mshwari&nbsp;, KCB MPesa, MCoop cash, Eazzy Loan, Timiza, HF Whizz)|
E2__6:E2__6  Digital loans that you get through the phone that you download through apps (e.g. Branch, Tala, Utunzi, Haraka loans, etc.)|
E2__99:E2__99  Refused to Answer (DO NOT READ OUT)|
E3__1:E3__1  Lack of collateral|
E3__9:E3__9  Income is low and unable to repay|
E3__16:E3__16  No money to loan out|
E3__18:E3__18  Members defaulting/not cleared loans|
E3__19:E3__19  Loan limit|
E3__99:E3__99  Refused to Answer (DO NOT READ OUT)|
E1iA:E1iA. Number of Personal loan from a bank/ business|
E1iiA:E1iiA. Number of outstanding Personal loan from a bank/ business|
E1iiiA:E1iiiA MAIN reason for taking Personal loan from a bank/ business|
E1ivA:E1ivA.Collateral / security for Personal loan from a bank/ business|
E1vA:E1vA. Frequency of paying - Personal loan from a bank/ business|
E1viA:E1viA. Payments ways of Personal loan from a bank/ business|
E1viiA:E1viiA. Amount of  Personal loan from a bank/ business|
E1viiiA:E1viiiA. time when borrowed Personal loan from a bank/ business|
E1ixA:E1ixA. When expected to finish repaying - Personal loan from a bank/ business|
E1iB:E1iB. Number of Mobile bank (e.g. MShwari, KCB MPesa) loans|
E1iiB:E1iiB. Number of outstanding Mobile bank (e.g. MShwari, KCB MPesa) loan|
E1iiiB:E1iiiB. MAIN reason for taking loan - Mobile bank (e.g. MShwari, KCB MPesa)|
E1viiB:E1viiB. Amount borrowed - Mobile bank (e.g. MShwari, KCB MPesa, MCoop Cash) loan|
E1viiiB:E1viiiB.When did you borrow - Loan from Mobile bank|
E1ixB:E1ixB. When expected to finish repaying- Mobile bank|
E1iiiC:E1iiiC. MAIN reason for taking loan - Loan at a Sacco|
E1ivC:E1ivB. Collateral / security for Sacco|
E1vC:E1vC. Frequency of paying -  Sacco (Savings and Credit Cooperative Society) loan|
E1viC:E1viC. Ways of repayment for Loan from Sacco|
E1viiC:E1viiC. Amount borrowed - Loan from Sacco|
E1viiiC:E1viiiC.When did you borrow - Loan from Sacco|
E1iiiD:E1iiiD. MAIN reason for taking loan -  Loan from a microfinance institution|
E1ivD:E1ivD.Collateral / security for -  Microfinance institution loan|
E1vD:E1vD. Frequency of paying -  Loan from Microfinance institution|
E1viD:E1viD. Ways of repayment for Loan from Microfinance institution|
E1viiD:E1viiD. Amount borrowed - Loan from Microfinance institution|
E1viiiD:E1viiiD.When did you borrow - Loan from Microfinance institution|
E1iiiE:E1iiiE. MAIN reason for taking loan -  Loan from Moneylender/Shylock|
E1ivE:E1ivE. Collateral / security for -  Moneylender/Shylock loan|
E1vE:E1vE. Frequency of paying - Loan from Moneylender/Shylock|
E1viE:E1viE. Ways of repayment for Moneylender/Shylock|
E1viiE:E1viiE. Amount borrowed - Loan from Moneylender/Shylock|
E1viiiE:E1viiiE.When did you borrow - Loan from Moneylender/Shylock|
E1iiF:E1iiF. Number of outstanding loans - Group/chama|
E1iiiF:E1iiiF. MAIN reason for taking loan -  Loan from Group/chama|
E1ivF:E1ivF.Collateral / security for -   Group/chama loan|
E1vF:E1vF. Frequency of paying - Loan from Group/chama|
E1viF:E1viF. Ways of repayment for Loan from Group/chama|
E1viiF:E1viiF. Amount borrowed -Loan from Group/chama|
E1viiiF:E1viiiF.When did you borrow - Loan from Group/chama|
E1iiG:E1iiG. Number of outstanding loan - Government institution for education|
E1iiiG:E1iiiG. MAIN reason for taking loan - from Government institution for education|
E1vG:E1vG. Frequency of paying - Loan from Government inst|
E1viG:E1viG. Ways of repayment for Loan from Government institution|
E1viiG:E1viiG. Amount borrowed - Loan from Government institution for education)|
E1viiiG:E1viiiH.When did you borrow - Loan from Government institution for education|
E1iH:E1iH Loan from Employer|
E1iiH:E1iiH. Number of outstanding loans -  Loan from Employer|
E1iiiH:E1iiiH. MAIN reason for taking loan - Loan from Employer|
E1ivH:E1ivH.Collateral / security for -   Loan from Employer|
E1vH:E1vH. Frequency of paying - Loan from Employer|
E1viH:E1viH. Ways of repayment for Loan from Employer|
E1viiH:E1viiH. Amount borrowed - Loan from Employer|
E1viiiH:E1viiiH.When did you borrow - Loan from Employer|
E1iI:E1iI Loan from family/friend/neighbour|
E1iiI:E1iiI. Number of outstanding loans - Loan from family/friend/neighbour|
E1iiiI:E1iiiI. MAIN reason for taking loan - Loan from family/friend/neighbour|
E1vI:E1vI. Frequency of paying -  Loan from Family / friend / neighbour|
E1viI:E1viI. Ways of repayment for Loan from Family / friend / neighbour|
E1viiI:E1viiI. Amount borrowed - Loan from Family / friend / neighbour|
E1viiiI:E1viiiI.When did you borrow - Loan from Family / friend / neighbour|
E1iJ:E1iJ Cash loan from shopkeeper|
E1iiJ:E1iiJ. Number of outstanding loans - Cash loan from shopkeeper|
E1iiiJ:E1iiiJ. MAIN reason for taking loan - Cash loan from shopkeeper|
E1iiiJi:E1iiiJi. Other reason Cash loan from shopkeeper|
E1vJ:E1vJ. Frequency of paying -  Loan from Cash from Shopkeeper|
E1vJi:E1vJi. Other frequency of  repayment for Loan from Cash from Shopkeeper|
E1viJ:E1viJ. Ways of repayment for Cash from shop keeper|
E1viJi:E1viJi. Other repayment ways for Cash from Shopkeeper|
E1viiJ:E1viiJ. Amount borrowed - Cash from Shopkeeper|
E1viiiJ:E1viiiJ. When did you borrow - Loan from Cash from Shopkeeper|
E1iiiK:E1iiiK. MAIN reason for taking loan - products on credit from a shopkeeper|
E1vKi:E1vKi. Other repayments frequency taking products on credit from a shopkeeper|
E1viK:E1viK Ways of repayment for taking products on credit from a shopkeeper|
E1viKi:E1vKi. Other frequency of  repayment taking products on credit from a shopkeeper|
E1viiK:E1viiK. Amount borrowed - Taking goods and services on credit from a shopkeeper|
E1viiiK:E1viiiK.When did you borrow - products on credit from a shopkeeper|
E1iL:E1iL Digital loans app (e.g. Tala, Branch, Utunzi, Haraka Loans)|
E1iiL:E1iiL. Number of outstanding loans -  Digital loans app (e.g. Tala)|
E1iiiL:E1iiiL. MAIN reason for taking loan -Digital loans app (e.g. Tala)|
E1iiiLi:E1iiiLi. Other Digital loans app (e.g. Tala, Branch, Utunzi, Haraka Loans)|
E1vL:E1vL. Frequency of paying -  Digital loans app (e.g. Tala)|
E1vLi:E1vLi. Other frequency of  repayment for Digital loans app (e.g. Tala, Branch)|
E1viL:E1viL. Ways of repayment for Digital loans app (e.g. Tala, Branch)|
E1viLi:E1viLi. Other ways repayment for Digital loans app|
E1viiL:E1viiL. Amount borrowed - Digital loans app (e.g. Tala)|
E1viiiL:E1viiiL.When did you borrow Digital loans app (e.g. Tala)|
E1ixL:E1ixL. When expected to finish -Digital loans app (e.g. Tala)|
E1xL:E1xL. Amount outstanding -  Digital loans app (e.g. Tala, Branch)|
E1iiiM:E1iiiM. MAIN reason for taking loan - Loan/credits from buyer of your harvest|
E1iiiMi:E1iiiMi. Other Loan/credits from buyer of your harvest, (e.g. tobacco)|
E1vM:E1vM. Frequency of paying -  Loan/credits from buyer of your harvest|
E1vMi:E1vMi. Other frequency of  repayment for Loan/credits from buyer of your harvest|
E1viM:E1viM. Ways of repayment for Loan/credits from buyer of your harvest|
E1viMi:E1viMi. Other ways  your repayment  Loan/credits from buyer of your harvest|
E1viiM:E1viiM. Amount borrowed - Loan/credits from buyer of your harvest|
E1viiiM:E1viiiQ.When did you borrow - Loan/credits from buyer of your harvest|
E1ixM:E1ixM. When expected to finish - Loan/credits from buyer of your harvest|
E1xM:E1xM. Amount outstanding -  Loan/credits from buyer of your harvest|
E1iiN:E1iiN. Number of outstanding loans - Hire purchase (e.g. A.R.T., Amedo)|
E1iiiN:E1iiiN. MAIN reason for taking loan - Hire purchase (e.g. A.R.T., Amedo)|
E1vNi:E1vFi. Other frequency of  repayment for Hire purchase (e.g. A.R.T., Amedo)|
E1viN:E1viC. Ways of repayment for Hire purchase (e.g. A.R.T., Amedo)|
E1viNi:E1viNi. Other way of repayment for Hire purchase loan|
E1viiN:E1viiN. Amount borrowed - Hire purchase|
E1viiiN:E1viiiN. When did you borrow - Hire purchase (e.g. A.R.T)|
E1iiO:E1iiO. Number of outstanding loans - Loan from Insurance|
E1iiiO:E1iiiO. MAIN reason for taking loan - Loan from Insurance|
E1iiiOi:E1iiiOi. Other Loan from Insurance|
E1ivO:E1ivO.Collateral / security for -   Loan from Insurance|
E1ivOi:E1ivOi.Other collateral / security for   Loan from Insurance|
E1vO:E1vO. Frequency of paying - Loan from Insurance|
E1vOi:E1vOi. Other frequency of  repayment for Loan from Insurance|
E1viO:E1viO. Ways of repayment for Loan from Insurance|
E1viOi:E1viCi. Other Loan from Insurance|
E1viiO:E1viiO. Amount borrowed - Loan from Insurance|
E1viiiO:E1viiiO. When did you borrow - Loan from Insurance|
E1ixO:E1ixO. When expected to finish - Loan from Insurance|
E1xO:E1xO. Amount outstanding -  Loan from Insurance|
E1iP:E1iP Government or government related institution to buy a house or land|
E1iiP:E1iiP. Number of outstanding loans -  Govt or governmentrelated institution|
E1iiiP:E1iiiP. MAIN reason for taking loan - Government or govt related ins|
E1iiiPi:E1iiiPi. Other Government or govt related institution to buy a house or land|
E1ivP:E1ivP.Collateral / security for -   Government or govt related inst loan|
E1ivPi:E1ivPi.Other collateral / security for   Government or govt related inst|
E1vP:E1vP. Frequency of paying -  Government or government related inst|
E1vPi:E1vPi. Other frequency of  repayment for Government or govt related ins|
E1viP:E1viP. Ways of repayment for Government or government related inst loan|
E1viPi:E1viPi. Other way of repayment for Government or government related inst loan|
E1viiP:E1viiP. Amount borrowed - Loan from Government or government related inst|
E1viiiP:E1viiiP.When did you borrow - Loan from Government or governmentrelated inst|
E1ixP:E1ixP. When expected to finish - Loan from Insurance|
E1xP:E1xP. Amount outstanding -  Government or governmentrelated inst|
E1iiQ:E1iiQ. Number of outstanding loans - Overdraft|
E1iiiQ:E1iiiQ. MAIN reason for taking loan - Overdraft|
E1vQi:E1vQi. Other frequency of  repayment for an  Overdraft|
E1viQ:E1viQ. Ways of repayment for Overdraft|
E1viQi:E1viQi. Other way of repayment for Other Overdraft loan|
E1viiQ:E1viiQ. Amount borrowed - Overdraft|
E1viiiQ:E1viiiQ.When did you borrow - Overdraft|
E1iR:E1iR Mobile money loan provider e.g Fuliza|
E1iiR:E1iiR. Number of outstanding loans -  Mobile money loan provider e.g Fuliza|
E1iiiR:E1iiiR. MAIN reason for taking loan - Mobile money loan provider e.g Fuliza|
E1iiiRi:E1iiiRi Other Mobile money loan provider e.g Fuliza|
E1viiR:E1viiR. Amount borrowed - Mobile money loan provider e.g Fuliza|
E1viiiR:E1viiiR.When did you borrow - Mobile money loan provider e.g Fuliza|
E1ixR:E1ixR. When expected to finish - Mobile money loan provider e.g Fuliza|
E1iiiS:E1iiiS. MAIN reason for taking loan - Credit Card|
E1viS:E1viS. Ways of repayment for Credit Card loan|
E1viSi:E1viSi. Other ways of repayment for Other Credit Card|
E1viiAS:E1viiS. Amount borrowed Credit Card|
E1_ii1:E1_ii. Loan Features|
E1_ii2:E1_ii2 Loan Features|
E1_2:E1_2. loan restructuring/negotiation?|
E2A:E2A Amount of Repayment|
E2B1:E2B1 Ease of Loan Repayment|
E2B2:E2B2. Used savings to repay the loan|
E2B3:E2B3. Sold / gave assets or belongings to repay the loan|
E2B4:E2B4. Reduced expenditures on food products to repay the loan|
E2B5:E2B5. Reduced expenditures on nonfood products to repay the loan|
E2Ci__2:E2Ci__2  Paid late|
E2Ci__3:E2Ci__3  Missed a payment|
E2Ci__5:E2Ci__5  Never paid late/less or missed a payment|
E2Ci__99:E2Ci__99  Refused to Answer (DO NOT READ OUT)|
E2Cii:E2Cii. Number of Times Defaulted|
E2D__1:E2D__1  Loan from a bank/MFB|
E2D__2:E2D__2  Loan from mobile banking (e.g. Mshwari, KCB MPesa, MCoop, Eazzy Loan, Timiza, HF Whizz)|
E2D__3:E2D__3  Loan at a Sacco / Savings and Credit Cooperative society|
E2D__4:E2D__4  Loan from insurance company|
E2D__5:E2D__5  Loan from a microfinance institution|
E2D__6:E2D__6  Loan from Shylocks / Loan Sharks / Money Lenders / Money Merchants that are not from your phone (e.g. Platinum, Ngao, etc|
E2D__7:E2D__7  Loan from a group/chama|
E2D__8:E2D__8  Loan from a government institution for education, agriculture or a development loan (e.g. HELB, Agricultural Finance Corporation, Youth Fund, Women Fund)|
E2D__9:E2D__9  Loan from an employer|
E2D__10:E2D__10  Loan from family/friend/neighbour|
E2D__11:E2D__11  Cash loan from shopkeeper|
E2D__13:E2D__13  Digital loans that you get through the phone that you download through apps (e.g. Branch, Tala, Utunzi, KopaCredo, Haraka loans, etc.)|
E2D__14:E2D__14  Loan / credits from buyer of your harvest / supplier of agricultural inputs (e.g. coffee, tea, sugarcane, tobacco, vegetables)|
E2D__16:E2D__16  Loan to buy/build a house (mortgage), or to buy land from a bank or SACCO|
E2D__19:E2D__19  Loans from mobile money providers e.g fuliza|
E2D__99:E2D__99  Refused to Answer (DO NOT READ OUT)|
E2Di:E2Di. Loans Defaulted - other|
E2E:E2E. Reasons for Default|
E2Ei:E2Ei. Reasons for Default - Other|
E2F__2:E2F__2  Reduction in future loan limit|
E2F__4:E2F__4  Denied access to future loan with the same lender|
E2F__5:E2F__5  Denied access to future loan with another lender|
E2F__99:E2F__99  Refused to Answer  (DO NOT READ OUT)|
E2Fi:E2Fi  E2Fi. Default Consequences - Other|
E3A__4:E3A__4  Digital loans apps providers|
E3B__4:E3B__4  Digital loans apps providers|
F2__99:F2__99  Refused to Answer   (DO NOT READ OUT)|
F3__22:F3__22  For later in life/ For old age/retirement|
F3__99:F3__99  Refused to Answer (DO NOT READ OUT)|
F2D__99:F2D__99  Refused to Answer (DO NOT READ OUT)|
G1A1__99:G1A1__99  Refused to Answer (DO NOT READ OUT)|
G1A2__99:G1A2__99  Refused to Answer (DO NOT READ OUT)|
G1A3__99:G1A3__99  Refused to Answer (DO NOT READ OUT)|
G1A4__99:G1A4__99  Refused to Answer (DO NOT READ OUT)|
G1A5__99:G1A5__99  Refused to Answer (DO NOT READ OUT)|
G1A6__99:G1A6__99  Refused to Answer (DO NOT READ OUT)|
G1A7__99:G1A7__99  Refused to Answer (DO NOT READ OUT)|
G1A8__99:G1A8__99  Refused to Answer (DO NOT READ OUT)|
G1A9__99:G1A9__99  Refused to Answer (DO NOT READ OUT)|
H1B__4:H1B__4  The bank will not give me a loan|
H1B__99:H1B__99  Refused to Answer (DO NOT READ OUT)|
H1__99:H1__99  Refused to Answer  (DO NOT READ OUT)|
H2.99:H2.99  99 Refused to Answer  (DO NOT READ OUT)|
H3.99:H3.99  99 Refused to Answer  (DO NOT READ OUT)|
H4.99:H4.99  99 Refused to Answer  (DO NOT READ OUT)|
H7__99:H7__99  Refused to Answer (DO NOT READ OUT)|
H9__99:H9__99  Refused to Answer (DO NOT READ OUT)|
H10__2:H10__2  Lost money / Money missing from my account eg Cards/PIN fraud|
H11__4:H11__4  Identity theft (someone stole my identification details and took a loan under my name/withdrew money from my account|
H11__99:H11__99  Refused to Answer (DO NOT READ OUT)|
H13A__99:H13A__99  Refused to Answer  (DO NOT READ OUT)|
H13B__99:H13B__99  Refused to Answer (DO NOT READ OUT)|
I6__2:I6__2  Lost money / Money missing from my account|
I8A__99:I8A__99  Refused to Answer  (DO NOT READ OUT)|
I8B__99:I8B__99  Refused to Answer  (DO NOT READ OUT)|
J1__1:J1__1  Unexpected charges based on loan|
J1__5:J1__5  Money missing from account|
J1__6:J1__6  Delays in getting services/loans due to liquidity challenges|
J1__99:J1__99  Refused to Answer  (DO NOT READ OUT)|
J5__99:J5__99  Refused to Answer (DO NOT READ OUT)|
J6__1:J6__1  Unexpected charges based on loan|
J6__2:J6__2  Lost money / money missing from account|
J8A__4:J8A__4  J8A. Sacco  Services Redress:Contacted / went to another Government agency, not CBK or SASRA (e.g. CID, Police, Cooperitives Commissioners Office)|
J8A__99:J8A__99  Refused to Answer  (DO NOT READ OUT)|
J8B__4:J8B__4  Contact / go to another government agency, not CBK or SASRA (e.g. CID, Police, Cooperitives Commissioners Office)|
J8B__99:J8B__99  Refused to Answer  (DO NOT READ OUT)|
K2__99:K2__99  Refused to Answer  (DO NOT READ OUT)|
K4__99:K4__99  Refused to Answer  (DO NOT READ OUT)|
K10__99:K10__99  Refused to Answer  (DO NOT READ OUT)|
K14__99:K14__99  Refused to Answer  (DO NOT READ OUT)|
K16__99:K16__99  Refused to Answer  (DO NOT READ OUT)|
L1__1:L1__1  Unexpected charges related to your loan|
L1__3:L1__3  Delays in getting loan eg system down time/ slower approval process|
L1__4:L1__4  Applied for a loan but did not get|
L1__6:L1__6  Fraud. The digital loan service provider was fake|
L2__1:L2__1  Unexpected charges related to your loan|
L2__3:L2__3  Delays in getting loan eg system down time/ slower approval process|
L2__4:L2__4  Applied for a loan but did not get|
L2__6:L2__6  Fraud. The digital loan service provider was fake|
L3__99:L3__99  Refused to Answer  (DO NOT READ OUT)|
L3i:L3i  L3i. Digital Loan App Redress - Other|
M3__4:M3__4  Equitel/ Eazzy loan|
M3__99:M3__99  Refused to Answer (DO NOT READ OUT)|
M8__6:M8__6  Hostile loan repayment collection|
M9__3:M9__3  Identify theft (someone I don't know stole my identification details and took a loan under my name/withdrew money from my|
M9__4:M9__4  someone I know used my identification details and took a loan under my name/withdrew money from my account|
M11A__99:M11A__99  Refused to Answer  (DO NOT READ OUT)|
M11B__99:M11B__99  Refused to Answer  (DO NOT READ OUT)|
N2__99:N2__99  Refused to Answer(DO NOT READ OUT)|
N4__99:N4__99  Refused to Answer (DO NOT READ OUT)|
N5__99:N5__99  Refused to Answer (DO NOT READ OUT)|
N8__6:N8__6  Borrow from government( eg youth fund, women fund, uwezo fund)|
N10__4:N10__4  Through dishonesty or default by members|
N10__99:N10__99  Refused to Answer  (DO NOT READ OUT)|
O3__99:O3__99  Refused to Answer (DO NOT READ OUT)|
P5__18:P5__18  climate related|
P5__99:P5__99  Refused to Answer  (DO NOT READ OUT)|
P9:P9. Reason Loan Business|
P9i:P9. Reason Loan Business - other|
P15__99:P15__99  Refused to Answer (DO NOT READ OUT)|

In [9]:
# We take the metadata and search specifically for performance 'outcomes'
outcome_keywords = ['default', 'late', 'miss', 'distress', 'seized']
target_candidates = {k: v for k, v in risk_related.items() 
                     if any(word in v.lower() for word in outcome_keywords)}

# Print what we found
for col, label in target_candidates.items():
    print(f"{col}: {label}")

B1C3: B1C3. Frequency miss an important family event
E3__1: E3__1  Lack of collateral
E3__18: E3__18  Members defaulting/not cleared loans
E1ivA: E1ivA.Collateral / security for Personal loan from a bank/ business
E1ivC: E1ivB. Collateral / security for Sacco
E1ivD: E1ivD.Collateral / security for -  Microfinance institution loan
E1ivE: E1ivE. Collateral / security for -  Moneylender/Shylock loan
E1ivF: E1ivF.Collateral / security for -   Group/chama loan
E1ivH: E1ivH.Collateral / security for -   Loan from Employer
E1ivO: E1ivO.Collateral / security for -   Loan from Insurance
E1ivOi: E1ivOi.Other collateral / security for   Loan from Insurance
E1iP: E1iP Government or government related institution to buy a house or land
E1iiP: E1iiP. Number of outstanding loans -  Govt or governmentrelated institution
E1iiiP: E1iiiP. MAIN reason for taking loan - Government or govt related ins
E1iiiPi: E1iiiPi. Other Government or govt related institution to buy a house or land
E1ivP: E1ivP.Collateral / security for -   Government or govt related inst loan
E1ivPi: E1ivPi.Other collateral / security for   Government or govt related inst
E1vP: E1vP. Frequency of paying -  Government or government related inst
E1vPi: E1vPi. Other frequency of  repayment for Government or govt related ins
E1viP: E1viP. Ways of repayment for Government or government related inst loan
E1viPi: E1viPi. Other way of repayment for Government or government related inst loan
E1viiP: E1viiP. Amount borrowed - Loan from Government or government related inst
E1viiiP: E1viiiP.When did you borrow - Loan from Government or governmentrelated inst
E1xP: E1xP. Amount outstanding -  Government or governmentrelated inst
E2Ci__2: E2Ci__2  Paid late
E2Ci__3: E2Ci__3  Missed a payment
E2Ci__5: E2Ci__5  Never paid late/less or missed a payment
E2Cii: E2Cii. Number of Times Defaulted
E2Di: E2Di. Loans Defaulted - other
E2E: E2E. Reasons for Default
E2Ei: E2Ei. Reasons for Default - Other
E2Fi: E2Fi  E2Fi. Default Consequences - Other
F3__22: F3__22  For later in life/ For old age/retirement
H10__2: H10__2  Lost money / Money missing from my account eg Cards/PIN fraud
I6__2: I6__2  Lost money / Money missing from my account
J1__5: J1__5  Money missing from account
J6__2: J6__2  Lost money / money missing from account
J8A__4: J8A__4  J8A. Sacco  Services Redress:Contacted / went to another Government agency, not CBK or SASRA (e.g. CID, Police, Cooperitives Commissioners Office)
J8B__4: J8B__4  Contact / go to another government agency, not CBK or SASRA (e.g. CID, Police, Cooperitives Commissioners Office)
L1__1: L1__1  Unexpected charges related to your loan
L2__1: L2__1  Unexpected charges related to your loan
N10__4: N10__4  Through dishonesty or default by members
P5__18: P5__18  climate related
R2A__6: R2A__6  High costs related to a child birth
R2Ai__2: R2Ai__2  Experienced flooding/drought/climate related event
R2Ai__5: R2Ai__5  Experienced non- climate related loss e.g. theft,fire
R2Ai__6: R2Ai__6  High costs related to a child birth
R3C__11: R3C__11  Used/ accumulate savings held in mobile banking (e.g. MShwari, KCB MPesa, MCoop Cash, Eazzy Loan, Timiza, HF Whizz)
R3C__12: R3C__12  Used/ accumulate savings held in a mobile money provider / wallet (e.g. MPESA, Airtel Money, TCash, Tangaza, MobiKash, Equitel)
R3C__13: R3C__13  Used/ accumulate savings held at a group / chama
R3C__14: R3C__14  Used/ accumulate savings held with friends / family
R3C__15: R3C__15  Used/ accumulate savings held in a secret hiding place
S5__3: S5__3  Educational activities (undertaking online courses, finding education-related materials online)
S5__4: S5__4  Health related activities (seeking information/advice about medical conditions, finding hospitals etc.)
S5__5: S5__5  Employment and career related activities (searching for jobs/vacancies etc.)
defaulted: Defaulted on Loans/Debt
bank_usage: All commecial banks (+MFBs)  + mobile bank providers  regulated by CBK + Post Bank
insurance_usage: All users of insurance  regulated by IRA without NHIF
insurance_usage2: Insurance Companies (Regulated by IRA including NHIF) Usage
insurance_usage1: Insurance Usage Regulated by IRA including NHIF and NSSF
Digital_credit: Non bank non-regulated digital credit usage
paidlate: Paid Late
defaultloan: Loans default
E2Ci23: Paid late/ Missed a payment
On_time_borrowers: Never paid late/less/missed payment
Late_payer_borrowers: Paid late
any_defaulter: Defaulted at least once on any loan in the past
defaulted1234: Loan defaulters

### 2.1 The Logic of "High Risk"
In credit risk modeling, we must distinguish between **Input Features** (the borrower's characteristics) and **Output Labels** (the borrower's performance). To define our target variable ($y$), we performed a secondary search on the FinAccess 2021 metadata to isolate columns that represent **Credit Failure**.

We filtered the 100+ loan-related results by looking for "Outcome" keywords: *Default*, *Late*, *Missed*, and *Distress*.

### 2.2 Selecting the "Golden Trio"
From the search results, we settled on three primary columns to define a **"High Risk"** individual:

1. **`defaulted` (Defaulted on Loans/Debt):** This represents a "Hard Default" where the contractual obligation was completely broken.
2. **`paidlate` (Paid Late):** This represents "Arrears." In banking, this is an early warning sign of deteriorating creditworthiness.
3. **`E2Ci23` (Paid late/ Missed a payment):** This serves as a "Safety Net" variable to capture any instances of delinquency not recorded in the first two columns.

> **Note:** These three indicators are combined using a logical `OR` operation to create a binary label: 
> * **1 (High Risk):** If the individual meets *any* of the criteria above.
> * **0 (Low Risk):** If the individual has a clean repayment record.

### 2.3 Constructing the Composite Target
Because survey respondents may answer "Yes" to one indicator but "No" to another, we created a **Composite Binary Target** ($y$).

* **Target = 1 (High Risk):** Respondent answered "Yes" to *any* of the three indicators (Defaulted, Paid Late, or Distress).
* **Target = 0 (Low Risk):** Respondent has used credit but has no record of default or late payment.

This approach ensures the model has a robust **"Ground Truth"** to learn the patterns of financial distress in the Kenyan market.

In [10]:
print(f"column E2Ci23 description:{meta.column_names_to_labels.get('E2Ci23')} ")

column E2Ci23 description:Paid late/ Missed a payment

In [11]:
# we define the risk columns, that we chose earlier
target_columns=['defaulted','paidlate','E2Ci23']

In [12]:
# Now cause survey data mixes strings (yes) and numbers (1), we define what counts as risk value
risk_indicators=['yes',1,1.0,'defaulted']

In [13]:
# we create our composite target
df['is_high_risk'] = df[target_columns].apply(
    lambda row: 1 if any(val in risk_indicators for val in row.values) else 0, 
    axis=1
)

In [14]:
#we now compare the Low and high risk
counts=df['is_high_risk'].value_counts()
percentage=df['is_high_risk'].value_counts(normalize=True)*100
print("--- Target variable distribution ---")
print(f"Low risk(0):{counts[0]}({percentage[0]:.2f}%)")
print(f"High risk(1):{counts[1]}({percentage[1]:.2f}%)")

--- Target variable distribution ---
Low risk(0):14613(66.35%)
High risk(1):7411(33.65%)

### 2.4 Target Distribution and Market Analysis

Upon applying the composite logic, the dataset yielded the following distribution:

| Class | Label | Observations | Percentage |
| :--- | :--- | :--- | :--- |
| **Class 0** | Low Risk | 14,613 | 66.35% |
| **Class 1** | High Risk | 7,411 | 33.65% |



#### Key Observations:

* **High Signal Density:** A risk rate of **~34%** is significantly higher than traditional commercial bank NPL (Non-Performing Loan) ratios, which typically hover below 15%. This suggests that the FinAccess 2021 dataset captures a wide spectrum of the "informal" and "digital" credit market, where risk is more prevalent.
* **Model Feasibility:** From a Machine Learning perspective, this is a **well-balanced dataset**. We do not face a "Needle in a Haystack" problem (common in fraud detection). The model has a substantial number of "High Risk" examples (7,411) to learn the underlying patterns of default.
* **Reflecting the Kenyan Context:** This distribution aligns with the rapid growth of digital lending in Kenya (Fuliza, M-Shwari, and App-based loans), where accessibility is high but repayment distress is a documented socioeconomic challenge.

## 3. Predictor variables

In [15]:
#we now serach the metadata for potential predictor variables
feature_keywords=['age','gender','smartphone','mpesa','educ','income','chama','employmet']
potential_features={k:v for k,v in meta.column_names_to_labels.items()
if any(word in v.lower()for word in feature_keywords)}
for col,label in potential_features.items():
    print(f"{col}:{label}")

A15:A15. Language
A15i:A15i. Language
A17:A17. Not returned to complete their education
A19:A19. AGE OF RESPONDENT
A21:A21. Education Completed
A21i:A21i. Other Education level Completed
A23:A23. Female HH Highest Formal Education
A26__6:A26. Persons with disability:Difficulty in communicating using your usual language
B1EF6:B1EF6. Income from investments (e.g shares,rental)
B3A__1:B3A. Income Sources:farming (crops, keeping livestock, fishing, aquaculture)
B3A__2:B3A. Income Sources:employment
B3A__3:B3A. Income Sources:casual work
B3A__4:B3A. Income Sources:running own business/Self employment
B3A__5:B3A. Income Sources:money from  NGO / Government/Social transfer
B3A__6:B3A. Income Sources:renting,  land, house/rooms, equipment
B3A__7:B3A. Income Sources:Earning money from investments, e.g. shares, stocks
B3A__8:B3A. Income Sources:Pension/Annuity
B3A__9:B3A. Income Sources:Money / support from family / friends / spouse
B3I:B3I. Monthly Income (KSh)
C1_2:C1-2. Savings through mobile banking (e.g. Mshwari , KCB MPesa, MCoop cash, Eazzy Loan, Timiza, HF Whizz)?
C1_3:C1-3. Savings/keeping through mobile money account (e.g. MPESA, Airtel Money, TCash, Tangaza, MobiKash, Equitel)
C1_5:C1-5. Savings at a group or chama
C1_9:C1-9. Registered on Mobile money (e.g. MPESA, Airtel Money, TCash, Tangaza, Equitel)
C1_10:C1_10. Registered on Mobile bank (e.g. Mshwari , KCB MPesa, MCoop cash, Eazzy Loan, Timiza, HF Whizz)
C1_12:C1_12. Loan from mobile banking (e.g. Mshwari , KCB MPesa, MCoop cash, Eazzy Loan, Timiza, HF Whizz, Stawi loan, M-fanisi)
C1_17:C1_17. Loan from a group/chama
C1_18:C1_18. Loan from a government institution for education, agriculture or devt
C1_27:C1-27. Loan to buy / build a house (mortgage), or to buy land from a bank / building society or Sacco/Insurance/Government
C1_45:C1-45. Education policy
D1i__4:D1i__4  You do not need Pension because your family, friends, groups of friends, chama and relatives will help you in old age
D1i__5:D1i__5  You do not need pension because you have saved in other financial institutions/assets for your old age
D1i__6:D1i__6  You do not need Pension because I have educated my children and they will take care of me in old age
D1i__12:D1i__12  You do not need pension because in your family tree people die before reaching retirement age
D1i__15:D1i__15  Lack of National ID/ under 18 yrs of age/student
D1B__5:D1B__5  Insurance agents are dishonest
D1B__6:D1B__6  You do not need insurance because your family, friends, groups of friends, chama and relatives help you when you are in need
D1C__5:D1C__5  Insurance agents are dishonest
D1C__6:D1C__6  You do not need insurance because your family, friends, groups of friends, chama and relatives help you when you are in need
D2_8:D2_8. Education insurance
D3__27:D3__27  Broker/Agent
D5__6:D5__6  Compulsory for this policy provider (loan,mortgage,fire,life)
D5__7:D5__7  The agent convinced me
E2__4:E2__4  Mobile banking (e.g. Mshwari&nbsp;, KCB MPesa, MCoop cash, Eazzy Loan, Timiza, HF Whizz)
E2__10:E2__10  Chama/groups
E3__9:E3__9  Income is low and unable to repay
E3__14:E3__14  Discrimination (Gender/culture
E1iB:E1iB. Number of Mobile bank (e.g. MShwari, KCB MPesa) loans
E1iiB:E1iiB. Number of outstanding Mobile bank (e.g. MShwari, KCB MPesa) loan
E1iiiB:E1iiiB. MAIN reason for taking loan - Mobile bank (e.g. MShwari, KCB MPesa)
E1vB:E1vB. Frequency of paying -  Mobile bank (e.g. MShwari, KCB MPesa)
E1viiB:E1viiB. Amount borrowed - Mobile bank (e.g. MShwari, KCB MPesa, MCoop Cash) loan
E1xB:E1xB. Amount outstanding - Mobile bank (e.g. MShwari, KCB MPesa, MCoop Cash)
E1iF:E1iF Group/chama
E1iiF:E1iiF. Number of outstanding loans - Group/chama
E1iiiF:E1iiiF. MAIN reason for taking loan -  Loan from Group/chama
E1ivF:E1ivF.Collateral / security for -   Group/chama loan
E1vF:E1vF. Frequency of paying - Loan from Group/chama
E1viF:E1viF. Ways of repayment for Loan from Group/chama
E1viiF:E1viiF. Amount borrowed -Loan from Group/chama
E1viiiF:E1viiiF.When did you borrow - Loan from Group/chama
E1ixF:E1ixF. When expected to finish - Group/chama
E1xF:E1xF. Amount outstanding -  Group/chama
E1iG:E1iG Government institution for education, agriculture or development (e.g. HELB, Agr
E1iiG:E1iiG. Number of outstanding loan - Government institution for education
E1iiiG:E1iiiG. MAIN reason for taking loan - from Government institution for education
E1viiG:E1viiG. Amount borrowed - Loan from Government institution for education)
E1viiiG:E1viiiH.When did you borrow - Loan from Government institution for education
E1xG:E1xG. Amount outstanding -  Government institution for education
E1iO:E1iO Bank/building society or Sacco (mortgage) to buy/build a house, or to buy land
E1xR:E1xR. Amount outstanding - Mobile bank (e.g. MShwari, KCB MPesa, MCoop Cash)
E2B4:E2B4. Reduced expenditures on food products to repay the loan
E2B5:E2B5. Reduced expenditures on nonfood products to repay the loan
E2D__2:E2D__2  Loan from mobile banking (e.g. Mshwari, KCB MPesa, MCoop, Eazzy Loan, Timiza, HF Whizz)
E2D__7:E2D__7  Loan from a group/chama
E2D__8:E2D__8  Loan from a government institution for education, agriculture or a development loan (e.g. HELB, Agricultural Finance Corporation, Youth Fund, Women Fund)
E2D__16:E2D__16  Loan to buy/build a house (mortgage), or to buy land from a bank or SACCO
E2F__2:E2F__2  Reduction in future loan limit
E2F__16:E2F__16  Threatening messages and calls
F2__10:F2__10  Requires a regular income
F3__2:F3__2  For education for myself or others
F3__22:F3__22  For later in life/ For old age/retirement
G1A1__3:G1A1__3  A mobile money account (e.g  MPesa, Airtel Money)
G1A1__5:G1A1__5  Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
G1A2__3:G1A2__3  A mobile money account (e.g  MPesa, Airtel Money)
G1A2__5:G1A2__5  Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
G1A3__3:G1A3__3  A mobile money account (e.g  MPesa, Airtel Money)
G1A3__5:G1A3__5  Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
G1A3__19:G1A3__19  Deducted from salary/Income
G1A4__3:G1A4__3  A mobile money account (e.g  MPesa, Airtel Money)
G1A4__5:G1A4__5  Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
G1A5__3:G1A5__3  A mobile money account (e.g  MPesa, Airtel Money)
G1A5__5:G1A5__5  Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
G1A6__3:G1A6__3  A mobile money account (e.g  MPesa, Airtel Money)
G1A6__5:G1A6__5  Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
G1A7__3:G1A7__3  A mobile money account (e.g  MPesa, Airtel Money)
G1A7__5:G1A7__5  Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
G1A8__3:G1A8__3  A mobile money account (e.g  MPesa, Airtel Money)
G1A8__5:G1A8__5  Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
G1A9__3:G1A9__3  A mobile money account (e.g  MPesa, Airtel Money)
G1A9__5:G1A9__5  Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
H1B__5:H1B__5  I don’t have a regular income
H1B__18:H1B__18  I can do all the transactions I need using a different kind of institutions (e.g. chama or Sacco)
H5:H5  H5. 90 Day Usage Bank
H7__2:H7__2  At a bank agent
H10__3:H10__3  Poor service received at a branch / agent / customer care
H13A__1:H13A__1  Went to the bank / bank manager Go to the bank/ bank manager
H13A__4:H13A__4  Contacted / went to another Government agency, not CBK (e.g. CID, Police, ) Contact / go to another government agency, not CBK (e.g. CID, Police,
H13B__1:H13B__1  Go to the bank/ bank manager
H13B__4:H13B__4  Contact / go to another government agency, not CBK (e.g. CID, Police)
I3:I3. Months Usage MFI
I6__3:I6__3  Poor service received at a branch / agent / customer care
I8A__1:I8A__1  Went to the MFI / MFI manager / relationship manager
I8A__2:I8A__2  I8A. MFI Services Redress:Called / Went to MFI agent
I8A__4:I8A__4  I8A. MFI Services Redress:Contacted / went to another Government agency, not CBK (e.g. CID, Police, Kenya Deposit Insurance Corporation)
I8B__1:I8B__1  Go to the MFI / MFI manager / relationship manager
I8B__2:I8B__2  Call / go to MFI agent
I8B__4:I8B__4  Contact / go to another government agency, not CBK (e.g. CID, Police, Kenya Deposit Insurance Corportation)
J1__3:J1__3  Poor service received at a branch or agent
J3:J3. 6 months UsageSacco
J5__6:J5__6  Sacco Agent
J8A__1:J8A__1  Went to the Sacco management
J8A__4:J8A__4  J8A. Sacco  Services Redress:Contacted / went to another Government agency, not CBK or SASRA (e.g. CID, Police, Cooperitives Commissioners Office)
J8B__1:J8B__1  Go to the Sacco management
J8B__4:J8B__4  Contact / go to another government agency, not CBK or SASRA (e.g. CID, Police, Cooperitives Commissioners Office)
K2__11:K2__11  Mobile agents are untrustworthy or fraudulent
K4__1:K4__1  MPesa
K5i:K5i. Mobile money accounts per Product/ service - Mpesa
K12__3:K12__3  Agent float unavailability
K12__4:K12__4  Being unable to get to an agent
K12__6:K12__6  Fraud / attempted fraud ( eg recieved less money from the agent)
K12__7:K12__7  Poor service received at branch / agent / customer care
K13__3:K13__3  Agent float unavailability
K13__4:K13__4  Being unable to get to an agent
K13__6:K13__6  Fraud / attempted fraud ( eg recieved less money from the agent)
K13__7:K13__7  Poor service received at branch / agent / customer care
K14__1:K14__1  Went to a mobile money shop / agent
K14__3:K14__3  Went to a Government agency (e.g. CBK AntiFraud unit/DCI /Police)
K16__5:K16__5  Recipient did not get the money but my account was deducted
K16__9:K16__9  Wrong Agent/Till  number
L1__7:L1__7  Harassment /Listing on social sites(Pushy messages / threats from provider )
L2__7:L2__7  Harassment /Listing on social sites(Pushy messages / threats from provider )
L3__5:L3__5  Go to a Government agency (e.g. CBK AntiFraud unit, CID, Police)
M3__2:M3__2  KCB MPesa
M8__4:M8__4  Fraud / attempted fraud ( e.g. received less money from the agent)
M8__5:M8__5  Poor service received at branch / agent / customer care
M11A__1:M11A__1  Went to the bank/mobile money provider relationship manager
M11A__2:M11A__2  M11A. Mobile Banking Services Redress:Called / Went to bank/mobile money provider agent
M11A__4:M11A__4  M11A. Mobile Banking Services Redress:Contacted / went to another Government agency, not CBK (e.g. CID, Police, Kenya Deposit Insurance Corporation)
M11B__1:M11B__1  Went to the bank/mobile money provider relationship manager
M11B__2:M11B__2  M11B. Mobile Banking Services Redress:Called / Went to bank/mobile money provider agent
M11B__4:M11B__4  M11B. Mobile Banking Services Redress:Contacted / went to another Government agency, not CBK (e.g. CID, Police, Kenya Deposit Insurance Corporation)
N1:N1  N1. Somebody Else's Chama Account
N2__9:N2__9  Unavailability of chama/groups within the area
O3__1:O3__1  Chama / Welfare groups
P5__8:P5__8  Suppliers closed down/reduced opertaing hours/no stock
P12__1:P12__1  Till number (e.g. Lipa na MPesa, Equitel) for merchant payments
P15__3:P15__3  A mobile money account (e.g  MPesa, Airtel Money)
P15__5:P15__5  Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
Q1i:Q1i  Q1. Agriculture Income - Other
Q2a__11:Q2a__11  Lack of storage facilities
Q7__3:Q7__3  A mobile money account (e.g  MPesa, Airtel Money)
Q7__5:Q7__5  Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
R1Ci__2:R1Ci__2  Borrowed from mobile banking (e.g. MShwari, KCB MPesa, MCoop Cash, Eazzy Loan, Timiza, HF Whizz)
R1Ci__5:R1Ci__5  Borrowed from group / chama
R1Ci__12:R1Ci__12  Used savings held in mobile banking (e.g. MShwari, KCB MPesa, MCoop Cash, Eazzy Loan, Timiza, HF Whizz)
R1Ci__13:R1Ci__13  Used savings held in a mobile money provider / wallet (e.g. MPESA, Airtel Money, TCash, Tangaza,  Equitel)
R1Ci__14:R1Ci__14  Used savings held at a group / chama
R2A__2:R2A__2  Loss or damage due to flooding/unseasonal rainfall/drought/locusts or pests, fire or other natural disaster
R2A__3:R2A__3  Death of main income earner
R2A__4:R2A__4  Death of a family member or other relative (not main income earner)
R2A__5:R2A__5  Loss or damage due to theft or violence including political violence
R2A__7:R2A__7  Loss of a job or a source of income or a wage cut
R2Ai__3:R2Ai__3  Death of main income earner
R2Ai__4:R2Ai__4  Death of a family member or other relative (not main income earner)
R2Ai__7:R2Ai__7  Loss of a job or a source of income or a wage cut
R2C__3:R2C__3  Borrowed from mobile banking (e(e.g. MShwari, KCB MPesa, MCoop Cash, Eazzy Loan, Timiza, HF Whizz)
R2C__5:R2C__5  Borrowed from group / chama
R2C__12:R2C__12  Used savings held in mobile banking (e.g. MShwari, KCB MPesa, MCoop Cash, Eazzy Loan, Timiza, HF Whizz)
R2C__13:R2C__13  Used savings held in a mobile money provider / wallet (e.g. MPESA, Airtel Money, TCash, Tangaza, Equitel)
R2C__14:R2C__14  Used savings held at a group / chama
R3C__2:R3C__2  Borrowed from mobile banking (e(e.g. MShwari, KCB MPesa, MCoop Cash, Eazzy Loan, Timiza, HF Whizz)
R3C__4:R3C__4  Borrowed from group / chama
R3C__11:R3C__11  Used/ accumulate savings held in mobile banking (e.g. MShwari, KCB MPesa, MCoop Cash, Eazzy Loan, Timiza, HF Whizz)
R3C__12:R3C__12  Used/ accumulate savings held in a mobile money provider / wallet (e.g. MPESA, Airtel Money, TCash, Tangaza, MobiKash, Equitel)
R3C__13:R3C__13  Used/ accumulate savings held at a group / chama
R3C__23:R3C__23  Education insurance
S5__3:S5__3  Educational activities (undertaking online courses, finding education-related materials online)
T2:T2. Average Cost to Nearest Financial Advisor?
T2i:T2. Average Cost to Nearest Financial Advisor- Other
T3:T3. Average Time to Financial Provider?
T3i:T3. Average Time to Financial Provider - Other
T4i:T4. Average Cost to Nearest Bank - Other
T5:T5. Average time to Walk to the Nearest Bank
T5i:T5. Average time to Walk to the Nearest Bank - Other
T6:T6. Average Cost to the Nearest Mobile Money Agent
T6i:T6. Average Cost to the Nearest Mobile Money Agent - Other
T7:T7. Average Time to Walk to the Nearest Mobile Money Agent
T7i:T7. Average Time to Walk to the Nearest Mobile Money Agent - Other
T8:T8. Average Cost to Nearest Bank agent
T8i:T8. Average Cost to Nearest Bank agent - Other
T9:T9. Average time to Walk to the Nearest Bank agent
T9i:T9i. Other Average time to Walk to the Nearest Bank agent
U21__2:U21__2  Used regular income to buy materials whenever possible
U24d:U24d. Rent / mortgage on your home
gender:Selected Respondent Gender
agegroup:Age Group
education:Education level of Respondent
education_femHH:Education level of Female HH
education_anyHH:Education level of any HH member
savings_usage:Savings Usage overall
savings_formal:Savings usage:formal
savings_informal:Savings usage:informal
savings_excluded:Savings usage:Excluded
loan_usage:Loan Usage overall
loan_formal:Loan Usage formal
loan_informal:Loan Usage informal
bank_usage1:Commercial Bank Usage excluding Postbank
bank_usage3:Commercial Bank Usage excluding Mshwari/KCB Mpesa
bank_usage2:Commercial Bank Usage excluding Mobile Banking and Postbank
insurance_usage2:Insurance Companies (Regulated by IRA including NHIF) Usage
insurance_usage1:Insurance Usage Regulated by IRA including NHIF and NSSF
nhif_usage:NHIF usage
nssf_usage:NSSF usage
pension_usage:Pension usage
pension_usage_2:Pension usage less NSSF
mobile_bank_usage:Mobile Banking Usage
mobile_money_usage:Mobile Money Usage
digital_acc:Digital Account Usage
nonmfb_usage:nonmfb usage
mfi_usage:MFI Usage
sacco_usage:SACCO Usage
online_curr:Online Account Usage
investment_usage:Investment Usage
infgp_usage:Informal Group Usage ASCA/ROSCA/CHAMA) including include group chama investments, savings with group of friends
infgp_overall_usage:Informal Group Usage overall
formal_prudential:Formal Prudential - Commercial Banks, MFBs, DTSs, Insurance, Capital Markets, MShwari/KCB Mpesa
dts_usage_1:Deposit Taking SACCO Usage
dts_usage:Deposit Taking SACCO Usage
non_dts_usage_1:Non-Deposit Taking SACCO Usage
non_dts:Non-Deposit Taking SACCO Usage
non_dts_usage:Non-Deposit Taking SACCO Usage
Digital_credit:Non bank non-regulated digital credit usage
incomegp:Income group
mfhi_33:savings, pension, investment for old age
manage_day2day1:Adults with ability to manage day to day
manage_day2day:Adults with ability to manage day to day
incomegpnew:Income group
mobile_bank_usage1:Mobile Banking Usage including Fuliza
age55:age55
age70:age70
G1A68__3:A mobile money account (e.g  MPesa, Airtel Money)
G1A68__5:Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
combine_C1_11_C1_27:Combined those with personal loans and mortgages
mse:All businesses as main source of income
woman1549:Woman Age 15- 49
mobile_bank_account:A mobile money account (e.g  MPesa, Airtel Money)
Paybill_TillNUmber:Pay bill  / Till number through mobile money (e.g  Lipa na MPesa, Pay Bill)
education_femHHcomp1:education_femHH==None
education_femHHcomp2:education_femHH==Primary
education_femHHcomp3:education_femHH==Secondary
education_femHHcomp4:education_femHH==Tertiary
education_femHHcomp5:education_femHH==No Female HH head
education_anyHHcomp1:education_anyHH==None
education_anyHHcomp2:education_anyHH==Primary
education_anyHHcomp3:education_anyHH==Secondary
education_anyHHcomp4:education_anyHH==Tertiary
education_anyHHcomp5:education_anyHH==No Female HH head
Borrowing_prevalence3:Borrowing from social network, shopkeepers, chama, employer or buyer
E2B_combined:Borrowed, sold assets, reduced food spending or removed children from school to repay in past year
Informal_only_credit_users:Only use loans from informal providers - shylocks, chama, employer, family/friends, shopkeeper
Informal_only_credit_users2:Only use loans from informal providers - shylocks, chama, employer, family/friends, shopkeeper
agegroup2022:New Age groups
incomegp_new:Income group

## 3.1 Feature Selection Strategy

To predict the `is_high_risk` target, we selected features across four dimensions:

1. **Demographics:** Age and Education are used as proxies for financial maturity and earning stability.
2. **Economic Indicators:** We look beyond total income to examine *Income Sources* (e.g., Casual work vs. Employment), as cash-flow consistency is a key predictor of repayment.
3. **Digital Behavior:** Given Safaricom's ecosystem, we prioritize mobile money and mobile banking usage metrics as "Alternative Data" for credit scoring.
4. **Social Resilience:** We include participation in informal groups (Chamas) and exposure to recent economic shocks (e.g., job loss or family bereavement) to assess a borrower's support system.

In [16]:
#we now define the features (x) and the variable (y)
selected_columns=[
    #target
    'is_high_risk',

    #demographics
    'A19', #age
    'gender', #gender
    'education', #education level
    #economic
    'B3I', #monthly income
    'incomegpnew',#income group
    'B3A__2', #income souce:employment
    'B3A__3',#income soucre: casual
    #digita/financial behaviour
    'mobile_money_usage',
    'mobile_bank_usage',
    'infgp_usage', #chama usage
    'savings_usage'    
]

In [17]:
#we now slice the dataset to have only the relevant features
df_model=df[selected_columns].copy()

In [18]:
df_model.head(20)

,is_high_risk,A19,gender,education,B3I,incomegpnew,B3A__2,B3A__3,mobile_money_usage,mobile_bank_usage,infgp_usage,savings_usage
0,0,59.0,2.0,4.0,13000.0,5.0,1.0,0.0,1.0,3.0,1.0,1.0
1,0,43.0,2.0,4.0,6000.0,4.0,1.0,0.0,1.0,3.0,1.0,1.0
2,0,72.0,1.0,2.0,1000.0,1.0,0.0,0.0,3.0,3.0,1.0,1.0
3,0,22.0,1.0,2.0,2500.0,2.0,0.0,1.0,1.0,3.0,3.0,1.0
4,1,24.0,1.0,3.0,6000.0,4.0,1.0,0.0,1.0,1.0,1.0,1.0
5,1,50.0,1.0,2.0,4000.0,3.0,0.0,1.0,1.0,3.0,3.0,3.0
6,0,31.0,1.0,2.0,7000.0,4.0,0.0,1.0,1.0,3.0,3.0,1.0
7,0,38.0,1.0,2.0,3000.0,2.0,0.0,0.0,1.0,1.0,3.0,1.0
8,0,31.0,2.0,2.0,3000.0,2.0,0.0,0.0,1.0,3.0,3.0,1.0
9,0,62.0,2.0,1.0,NaN,9.0,0.0,0.0,3.0,3.0,1.0,1.0
10,1,35.0,1.0,2.0,400.0,1.0,1.0,0.0,1.0,3.0,3.0,1.0
11,0,35.0,2.0,1.0,20000.0,5.0,0.0,0.0,3.0,3.0,3.0,3.0
12,1,39.0,1.0,2.0,15000.0,5.0,0.0,1.0,1.0,3.0,3.0,1.0
13,0,53.0,2.0,3.0,4000.0,3.0,0.0,0.0,1.0,3.0,1.0,1.0
14,0,17.0,1.0,3.0,1000.0,1.0,0.0,1.0,3.0,3.0,3.0,1.0
15,0,40.0,2.0,3.0,500.0,1.0,0.0,0.0,1.0,3.0,3.0,1.0
16,0,22.0,1.0,4.0,1000.0,1.0,0.0,0.0,1.0,1.0,3.0,1.0
17,0,75.0,2.0,1.0,NaN,9.0,0.0,0.0,3.0,3.0,3.0,2.0
18,1,38.0,1.0,2.0,10000.0,4.0,0.0,1.0,1.0,2.0,3.0,1.0
19,1,35.0,2.0,2.0,2000.0,2.0,0.0,1.0,1.0,3.0,1.0,1.0

In [19]:
#lets get a concise  summary of our new dataset
df_model.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22024 entries, 0 to 22023
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   is_high_risk        22024 non-null  int64
 1   A19                 22024 non-null  float64
 2   gender              22024 non-null  float64
 3   education           22024 non-null  float64
 4   B3I                 19619 non-null  float64
 5   incomegpnew         22024 non-null  float64
 6   B3A__2              22024 non-null  float64
 7   B3A__3              22024 non-null  float64
 8   mobile_money_usage  22024 non-null  float64
 9   mobile_bank_usage   22024 non-null  float64
 10  infgp_usage         22024 non-null  float64
 11  savings_usage       22024 non-null  float64
dtypes: float64(11), int64(1)
memory usage: 2.0 MB

In [20]:
#lets check for duplicates
df_model.duplicated().sum()

np.int64(2548)

### ____ we see that we have 2548 duplicates,
###  Deduplication Policy
We applied a strict deduplication policy, removing all identical observation rows. This ensures that the model evaluation reflects its ability to **generalize** to new, unseen individuals rather than simply recalling identical profiles present in the training set.

In [21]:
#we opt to drop them to avoid data leakage
df_model=df_model.drop_duplicates()
df_model.duplicated().sum()

np.int64(0)

In [22]:
#lets check for null values
df_model.isnull().sum()

is_high_risk             0
A19                      0
gender                   0
education                0
B3I                   1843
incomegpnew              0
B3A__2                   0
B3A__3                   0
mobile_money_usage       0
mobile_bank_usage        0
infgp_usage              0
savings_usage            0
dtype: int64

### ___ we see that B3I has 2405 null values
### 6.3 Strategic Handling of Missing Values
Rather than performing a simple listwise deletion (dropping 10% of the sample), we opted for a hybrid imputation strategy:
- **Bias Mitigation:** Dropping rows would disproportionately remove informal-sector respondents, leading to selection bias.
- **Numerical Imputation:** Missing Income values were filled with the **Median** to preserve the distribution.

In [23]:
# we opt to fill\impute the missing values using the median
df_model['B3I']=df_model['B3I'].fillna(df_model['B3I'].median())
df_model.isnull().sum()

is_high_risk          0
A19                   0
gender                0
education             0
B3I                   0
incomegpnew           0
B3A__2                0
B3A__3                0
mobile_money_usage    0
mobile_bank_usage     0
infgp_usage           0
savings_usage         0
dtype: int64

In [24]:
# noew that our data is already encoded, we finalize the feature list
features=['A19','gender','education','B3I','incomegpnew','B3A__2','B3A__3', 'mobile_money_usage','mobile_bank_usage','infgp_usage','savings_usage']

In [25]:
#we convert codes to category types to ensure that the model does not see 2.0 for gender as the double of 1.0
categorical_cols=['gender','education','incomegpnew','B3A__2','B3A__3', 'mobile_money_usage','mobile_bank_usage','infgp_usage','savings_usage']
for col in categorical_cols:
    df_model[col]=df_model[col].astype('category')

In [26]:
#we create dummy variables(one hot encoding),this turns 'geneder into 1.0 and 2.0
X=pd.get_dummies(df_model[features],columns=categorical_cols,drop_first=True)
y=df_model['is_high_risk']

In [27]:
X.head()

,A19,B3I,gender_2.0,education_2.0,education_3.0,education_4.0,education_5.0,incomegpnew_2.0,incomegpnew_3.0,incomegpnew_4.0,...,B3A__2_1.0,B3A__3_1.0,mobile_money_usage_2.0,mobile_money_usage_3.0,mobile_bank_usage_2.0,mobile_bank_usage_3.0,infgp_usage_2.0,infgp_usage_3.0,savings_usage_2.0,savings_usage_3.0
0,59.0,13000.0,True,False,False,True,False,False,False,False,...,True,False,False,False,False,True,False,False,False,False
1,43.0,6000.0,True,False,False,True,False,False,False,True,...,True,False,False,False,False,True,False,False,False,False
2,72.0,1000.0,False,True,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
3,22.0,2500.0,False,True,False,False,False,True,False,False,...,False,True,False,False,False,True,False,True,False,False
4,24.0,6000.0,False,False,True,False,False,False,False,True,...,True,False,False,False,False,False,False,False,False,False

## Feature Engineering: Categorical Encoding
Since the dataset uses numerical mapping for categories (e.g., Education levels 1-4), we applied **One-Hot Encoding**. 
- **Rationale:** This prevents the model from assuming an "ordinal" relationship where none exists (e.g., assuming Gender 2 is "greater than" Gender 1). 
- **Dimensionality:** After encoding, our feature space expanded to accommodate the unique categories, providing the model with binary inputs for each attribute.

In [28]:
X.columns

Index(['A19', 'B3I', 'gender_2.0', 'education_2.0', 'education_3.0',
       'education_4.0', 'education_5.0', 'incomegpnew_2.0', 'incomegpnew_3.0',
       'incomegpnew_4.0', 'incomegpnew_5.0', 'incomegpnew_6.0',
       'incomegpnew_7.0', 'incomegpnew_8.0', 'incomegpnew_9.0',
       'incomegpnew_10.0', 'B3A__2_1.0', 'B3A__3_1.0',
       'mobile_money_usage_2.0', 'mobile_money_usage_3.0',
       'mobile_bank_usage_2.0', 'mobile_bank_usage_3.0', 'infgp_usage_2.0',
       'infgp_usage_3.0', 'savings_usage_2.0', 'savings_usage_3.0'],
      dtype='object')

In [29]:
X=X.astype(float)
X.head()

,A19,B3I,gender_2.0,education_2.0,education_3.0,education_4.0,education_5.0,incomegpnew_2.0,incomegpnew_3.0,incomegpnew_4.0,...,B3A__2_1.0,B3A__3_1.0,mobile_money_usage_2.0,mobile_money_usage_3.0,mobile_bank_usage_2.0,mobile_bank_usage_3.0,infgp_usage_2.0,infgp_usage_3.0,savings_usage_2.0,savings_usage_3.0
0,59.0,13000.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,43.0,6000.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,72.0,1000.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,22.0,2500.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,24.0,6000.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0